name: Vacations Bot as executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install cx_Freeze
          pip install -r requirements.txt

      - name: Build executable with cx_Freeze
        run: |
          python setup.py build

      - name: Copy static folder
        run: |
          mkdir -p build/static
          cp -r app/static/* build/static/

      - name: Compress to zip
        run: |
          cd build
          zip -r babybot-nancy.zip babybot.exe static/

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: babybot-nancy
          path: build/babybot-nancy.zip
