name: Vacations Bot as executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          python app/setup.py

      - name: Create directory for artifact
        run: |
          mkdir babybot
          cp dist/babybot.exe babybot/
          cp -r app/static babybot/

      - name: Print folder tree of ZIP contents
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: babybot
          depth: 3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: babybot-nancy
          path: babybot/
